version: '3'

services:
  microservice:
    restart: always
    build: ./project
    expose:
      - "8000"
    volumes:
      - app_volume:/usr/src/app/project/static
    command: /usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 wsgi
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_volume:/www/static
    depends_on:
      - microservice
volumes:
  app_volume:
    driver: local